### PR TITLE
feat(oauth): Add support for OAuth and Client API

### LINKED ISSUE #16: Add support for Client API with localStorage
This issue is to track doing OAuth properly, meaning store access + refresh tokens locally, and refresh the access token if it expires.

+ Design the interface so that the developer can provide their own storage strategy

PR to add this in AngularJS SDK is at https://github.com/stormpath/stormpath-sdk-angularjs/pull/195.

UAT: ensure login, registration, forgot password workflow, and email verification workflow work.
Even better: automate the above manual tests.

### PR DESCRIPTION
**Pull request by mraible**
An initial implementation that works to login/logout to Client API. 

To test this out, enable Client API for your application, then run `npm start` and add your domain as the endpoint. For example:

```
http://localhost:8000/?api=https://raible.apps.stormpath.io
```

You can also switch from the default storage implementation (localStorage) to cookies by padding in another `storage` parameter.

```
http://localhost:8000/?api=https://raible.apps.stormpath.io&storage=cookies
```

I configured Travis to run all the different combinations, but it'd probably be better to configure them as separate jobs. I'm not sure how to do that ATM.

Fixes #16.

### CODE REVIEW

**Comment by mraible** [comment]
Commenting on @robertjd's comment from #38:

> I tried adding &storage=cookies, but I’m still seeing the Authorization header being sent to the Client API?

My understanding is that we're supposed to store the authentication token in either cookies or localStorage. Regardless of which one we use, the value should be sent in the `Authorization` header. This works as illustrated by the following screenshots.

Cookies:

cookies

Local Storage: 

localstorage

**Comment by mraible** [comment]
RE: @robertjd's comment on #38:

> How can I test this in the “local” mode, e.g. against a local framework integration demo? I tried the sample project, and did npm link angular-stormpath, but I get this error (is there something else I need to do?):

I tried this as well, using `yarn link` in `stormpath-sdk-angular` and `yarn link angular-stormpath` in a new Angular CLI project.

I get the following errors when running `ng serve`:

```
RROR in ./src/app/app.component.ts
Module build failed: Error: /Users/mraible/ng-test/src/app/app.component.ts (24,5): Type 'Observable<boolean | Account>' is not assignable to type 'Observable<boolean | Account>'.
  Property 'source' is protected but type 'Observable<T>' is not a class derived from 'Observable<T>'.)
    at _checkDiagnostics (/Users/mraible/ng-test/node_modules/@ngtools/webpack/src/loader.js:116:15)
    at /Users/mraible/ng-test/node_modules/@ngtools/webpack/src/loader.js:141:17
 @ ./src/app/index.ts 1:0-32
 @ ./src/main.ts
 @ multi main

ERROR in ../dev/stormpath-sdk-angular/dist/esm/src/stormpath.module.js
Module not found: Error: Can't resolve 'ng2-webstorage' in '/Users/mraible/dev/stormpath-sdk-angular/dist/esm/src'
 @ ../dev/stormpath-sdk-angular/dist/esm/src/stormpath.module.js 22:0-47
 @ ../dev/stormpath-sdk-angular/dist/esm/src/index.js
 @ ./src/app/app.module.ts
 @ ./src/app/index.ts
 @ ./src/main.ts
 @ multi main

ERROR in ../dev/stormpath-sdk-angular/dist/esm/src/stormpath.module.js
Module not found: Error: Can't resolve 'angular2-cookie/core' in '/Users/mraible/dev/stormpath-sdk-angular/dist/esm/src'
 @ ../dev/stormpath-sdk-angular/dist/esm/src/stormpath.module.js 23:0-53
 @ ../dev/stormpath-sdk-angular/dist/esm/src/index.js
 @ ./src/app/app.module.ts
 @ ./src/app/index.ts
 @ ./src/main.ts
 @ multi main
```

The first one I've seen before. If you google for "Property 'source' is protected but type 'Observable<T>' is not a class derived from 'Observable<T>'.)", you'll find this happens with RxJS when using `npm link`.

The 2nd two errors, I'm not sure how to solve. It should be pulling in `ng-webstorage` and `angular2-cookie` as dependencies. They were in `peerDependencies`. I tried moving them to `dependencies`, but it doesn't seem to help.

**Comment by mraible** [comment]
The two missing dependencies (`ng-webstorage` and `angular2-cookie`) both seem to be caused by `npm link` not working with peer dependencies. https://github.com/npm/npm/issues/5875

**Comment by mraible** [comment]
@robertjd I was able to workaround the missing dependencies by manually installing `ng2-webstorage` and `angular2-cookie`. To solve the RxJS issue, I removed it from the symlinked project:

```
rm -rf node_modules/angular-stormpath/node_modules/rxjs
```

However, when I start things up, I get the following error:

```
Uncaught Error: Can't resolve all parameters for Stormpath: (?, ?, tokenStore).
    at CompileMetadataResolver._getDependenciesMetadata (http://localhost:4200/vendor.bundle.js:23123:19)
    at CompileMetadataResolver._getTypeMetadata (http://localhost:4200/vendor.bundle.js:23017:26)
    at http://localhost:4200/vendor.bundle.js:23167:41
    at Array.forEach (native)
    at CompileMetadataResolver._getProvidersMetadata (http://localhost:4200/vendor.bundle.js:23147:19)
    at CompileMetadataResolver._loadNgModuleMetadata (http://localhost:4200/vendor.bundle.js:22930:50)
    at CompileMetadataResolver._loadNgModuleSummary (http://localhost:4200/vendor.bundle.js:22803:31)
    at http://localhost:4200/vendor.bundle.js:22861:55
    at Array.forEach (native)
    at CompileMetadataResolver._loadNgModuleMetadata (http://localhost:4200/vendor.bundle.js:22848:49)
```

Maybe TypeScript Angular2 apps just don't work with `npm link`?

**Comment by robertjd** [comment]
👍 thanks @mraible !

**Pull request merged**
